// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiboSystemSummonerRift.Infrastructure.Data;

namespace NiboSystemSummonerRift.Infrastructure.Migrations
{
    [DbContext(typeof(SSRContext))]
    partial class SSRContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NiboSystemSummonerRift.ApplicationCore.Entity.TransactionEntity", b =>
                {
                    b.Property<int>("id_transaction")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<decimal>("Value")
                        .HasColumnType("NUMERIC(7,2)");

                    b.HasKey("id_transaction");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
